---
- name: show lb_api
  debug:
    msg: "{{ tmp_api | join(',') }}"
  failed_when: tmp_api is not defined

- name: show lb_api_listen
  debug:
    msg: "{{ tmp_api_listen | join(',') }}"
  failed_when: tmp_api_listen is not defined

- name: show lb_ingress_http_listen
  debug:
    msg: "{{ tmp_ingress_http_listen | join(',') }}"
  failed_when: tmp_ingress_http_listen is not defined

- name: show lb_ingress_http
  debug:
    msg: "{{ tmp_ingress_http | join(',') }}"
  failed_when: tmp_ingress_http is not defined

- name: show lb_ingress_https
  debug:
    msg: "{{ tmp_ingress_https | join(',') }}"
  failed_when: tmp_ingress_https is not defined

- name: show lb_ingress_https_listen
  debug:
    msg: "{{ tmp_ingress_https_listen | join(',') }}"
  failed_when: tmp_ingress_https_listen is not defined

- name: show lb_machine_config_server
  debug:
    msg: "{{ tmp_machine_config_server | join(',') }}"
  failed_when: tmp_machine_config_server is not defined

- name: show lb_machine_config_server_listen
  debug:
    msg: "{{ tmp_machine_config_server_listen | join(',') }}"
  failed_when: tmp_machine_config_server_listen is not defined
