---
- name: get total number of masters
  set_fact:
    master_count: "{{ item.qty }}"
    master_ip_octet: "{{ item.ip_octet }}"
  loop: "{{ ocp4_instances }}"
  when: item.name == "master"

- name: get total number of computes
  set_fact:
    compute_count: "{{ item.qty }}"
    compute_ip_octet: "{{ item.ip_octet }}"
  loop: "{{ ocp4_instances }}"
  when: item.name == "compute"

- name: create libvirt network
  template:
    src: nat_network.xml.j2
    dest: /tmp/network.xml
#  virt_net:
#    name: "{{ libvirt_network_name }}"
#    command: define
#    xml: '{{ (lookup("template", "nat_network.xml.j2")) }}'
#
