---
- name: check for user pull-secret
  stat:
    path: "{{ ocp4_pull_secret }}"
  register: pull_secret_file
  tags: [ setup ]

- name: fail if pull secret does
  fail:
    msg: "Please download your pull-secret from {{ pull_secret_request }} to {{ ocp4_pull_secret }}"
  when: not pull_secret_file.stat.exists
  tags: [ setup ]

- name: enable required firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ ocp4_firewall_ports }}"
  tags: [ setup ]

- name: import tasks install_podman.yml
  import_tasks: install_podman.yml

- name: import tasks ocp4_tools.yml
  import_tasks: ocp4_tools.yml

- name: import tasks create_ignitions.yml
  import_tasks: create_ignitions.yml

- name: deploy the podman container load balancer for OCP4
  import_role:
    name: openshift-4-loadbalancer
    tasks_from: create.yml
  vars:
    lb_name: "{{ ocp4_lb_container }}"
    lb_api: "{{ tmp_api | join(',') }}"
    lb_api_listen: "{{ tmp_api_listen | join(',') }}"
    lb_ingress_http: "{{ tmp_ingress_http | join(',') }}"
    lb_ingress_http_listen: "{{ tmp_ingress_http_listen | join(',') }}"
    lb_ingress_https: "{{ tmp_ingress_https | join(',') }}"
    lb_ingress_https_listen: "{{ tmp_ingress_https_listen | join(',') }}"
    lb_machine_config_server: "{{ tmp_machine_config_server | join(',') }}"
    lb_machine_config_server_listen: "{{ tmp_machine_config_server_listen | join(',') }}"
  when: not container_exist|bool and not tear_down|bool
  tags: [ lb, deploy_nodes ]

- name: deploy the podman container for hosting the required files for bootstrap
  import_role:
    name: ocp4-bootstrap-webserver
  tags: [ webserver, deploy_nodes ]

- name: import task download_rhcos_files.yml
  import_tasks: download_rhcos_files.yml
  when: not tear_down|bool

- name: Create the directory to store the virt-install scripts
  file:
    path: "{{ virtinstall_dir }}"
    state: directory
    owner: "{{ local_user_account }}"
  register: create_virtinstall_dir
  tags: [ deploy_nodes ]

- name: deploy a generated treeinfo that defines the location of the kernel and ramdisks
  template:
    src: treeinfo.j2
    dest: "{{ virtinstall_dir }}/.treeinfo"
    mode: "u=rw,g=r,o=r"
    owner: "{{ local_user_account }}"
  tags: [ deploy_nodes, rhcos ]

- name: import tasks deploy_libvirt_network.yml
  import_tasks: deploy_libvirt_network.yml

- name: import tasks configure_dns_entries.yml
  import_tasks: configure_dns_entries.yml
  tags: [ deploy_nodes, idm ]

- name: include build_cluster_nodes_profile.yml
  include_tasks: build_cluster_nodes_profile.yml
  loop: "{{ ocp4_instances }}"
  loop_control:
    loop_var: outer_item
    label: outer_item.name
  tags: [ deploy_nodes, rhcos, node_profile ]

- name: import tasks build_vm_list.yml
  import_tasks: build_vm_list.yml
  tags: [ deploy_nodes, rhcos, bootstrap ]

- name: deploy ocp4 nodes
  vars:
    vm_name: "{{ item }}"
  command: "{{ virtinstall_dir }}/{{ vm_name }}.sh"
  when: vm_name not in all_vms.list_vms
  loop: "{{ ocp4_nodes }}"
  delay: 10
  register: deploy_ocp4_nodes
  tags: [ deploy_nodes, rhcos ]

- name: include wait_for_vm_shutdown.yml
  include_tasks: wait_for_vm_shutdown.yml
  loop: "{{ ocp4_nodes }}"
  loop_control:
    loop_var: vm_name
    label: vm_name
  when: deploy_ocp4_nodes.changed
  tags: [ deploy_nodes, rhcos, rhcos_wait ]

- name: continue ocp4 bootstrap
  vars:
    vm_name: "{{ item }}"
  virt:
    name: "{{ vm_name }}"
    state: running
  loop: "{{ ocp4_nodes }}"
  delay: 10
  tags: [ deploy_nodes, bootstrap ]

- name: Waiting since {{ ansible_date_time.time }} for the bootstrap to complete
  command: |
    /usr/local/bin/openshift-install wait-for bootstrap-complete --dir "{{ openshift_install_dir }}" --log-level debug
  register: bootstrap_complete
  changed_when: false
  tags: [ deploy_nodes, bootstrap, postinstall ]

# BEGINS POST BOOTSTRAP STEPS
- name: set continue installation status
  set_fact:
    continue_install: "{{ true if bootstrap_complete.stderr.find('It is now safe to remove the bootstrap resources') != -1 else false }}"
#  when: bootstrap_complete.stderr.find('It is now safe to remove the bootstrap resources') != -1
  tags: [ deploy_nodes, bootstrap, postinstall ]

- name: list all libvirt vms
  virt:
    command: list_vms
  register: all_vms
  tags: [ deploy_nodes, rhcos, postinstall ]

- name: shutdown bootstrap nodes
  vars:
    vm_name: bootstrap
  virt:
    name: "{{ vm_name }}"
    state: shutdown
  register: shutdown_vms
  when: continue_install|bool and vm_name in all_vms.list_vms
  tags: [ deploy_nodes, rhcos, postinstall ]

- name: include wait_for_vm_shutdown.yml
  vars:
    vm_name: bootstrap
  include_tasks: wait_for_vm_shutdown.yml
  when: continue_install|bool and shutdown_vms.changed
  tags: [ deploy_nodes, rhcos, postinstall ]

- name: destroy bootstrap node
  vars:
    vm_name: bootstrap
  virt:
    name: "{{ vm_name }}"
    command: undefine
  when: continue_install|bool and vm_name in all_vms.list_vms
  tags: [ deploy_nodes, rhcos, postinstall ]

#- name: import tasks nfs_server.yml
#  import_tasks: nfs_server.yml
#  tags: [ deploy_nodes, rhcos, postinstall, nfs ]

- name: include enable_shutdown.yml
  include_tasks: enable_shutdown.yml
  tags: [ postinstall, enable_shutdown ]
