---
- name: Enable rhel-7-server-extras-rpms repository
  rhsm_repository:
    name: rhel-7-server-extras-rpms
    state: enabled
  tags: [ podman, pkg ]

- name: install podman, buildah, skopeo
  yum:
    name: "{{ podman_pkgs }}"
    state: present
  tags: [ podman, pkg ]

- name: activate namespaces
  become: True
  sysctl:
    name: user.max_user_namespaces
    value: '15000'
    sysctl_set: yes
    state: present
    reload: yes
  tags: [ podman ]

- name: check if subuid file exists
  stat:
    path: /etc/subuid
  register: subuid_setting
  tags: [ podman ]

- name: check if subgid file exists
  stat:
    path: /etc/subgid
  register: ssubgid_setting
  tags: [ podman ]

- name: Create /etc/subuid for non root podman exec
  copy:
    dest: "/etc/subuid"
    content: |
      {{ lookup('env','USER') }}:100000:65536
  when: subuid_setting.stat.exists == True
  tags: [ podman ]

- name: Create /etc/subgid for non root podman exec
  copy:
    dest: "/etc/subgid"
    content: |
      {{ lookup('env','USER') }}:100000:65536
  when: ssubgid_setting.stat.exists == True 
  tags: [ podman ]