---
# tasks file for ocp4-kvm-deployer
- name: import tasks pre_tasks.yml
  import_tasks: pre_tasks.yml

- name: import tasks tear_down.yml
  import_tasks: tear_down.yml
  when: tear_down|bool

- name: import task deploy.yml
  import_tasks: deploy.yml
  when: not tear_down|bool

