---
# delete folder virtinstall_dir
# delte network libvirt_network_name
# delete vms

- name: Remove load balancer container
  import_role:
    name: openshift-4-loadbalancer
    tasks_from: destroy.yml
  vars:
    lb_name: "{{ ocp4_lb_container }}"
    lb_api: "{{ tmp_api | join(',') }}"
    lb_api_listen: "{{ tmp_api_listen | join(',') }}"
    lb_ingress_http: "{{ tmp_ingress_http | join(',') }}"
    lb_ingress_http_listen: "{{ tmp_ingress_http_listen | join(',') }}"
    lb_ingress_https: "{{ tmp_ingress_https | join(',') }}"
    lb_ingress_https_listen: "{{ tmp_ingress_https_listen | join(',') }}"
    lb_machine_config_server: "{{ tmp_machine_config_server | join(',') }}"
    lb_machine_config_server_listen: "{{ tmp_machine_config_server_listen | join(',') }}"
  tags: [ lb ]

- name: Create OpenShift 4 bootstrap webserver
  import_role:
    name: ocp4-bootstrap-webserver
    tasks_from: tear_down.yml
  tags: [ webserver ]
  
- name: remove the ocp4 installation directory {{ openshift_install_dir }}
  file:
    path: "{{ openshift_install_dir }}"
    state: absent
  tags: [ lb ]